# Оглавление
1. [Матрицы и матричные операции. Часть 1](#matrix1)
    * [Задание 1](#matrix1_1)
    * [Задание 2](#matrix1_2)
    * [Задание 3](#matrix1_3)
    * [Задание 4](#matrix1_4)
    * [Задание 5](#matrix1_5)
2. [Матрицы и матричные операции. Часть 2](#matrix2)
    * [Задание 1](#matrix2_1)
    * [Задание 2](#matrix2_2)
    * [Задание 3](#matrix2_3)
    * [Задание 4](#matrix2_4)

In [1]:
import numpy as np

# Матрицы и матричные операции. Часть 1 <a class='anchor' id='matrix1'>

### Задание 1 <a class='anchor' id='matrix1_1'>
    
Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

а) $A$ — матрица $4 \times 2$, $B$ — матрица $4 \times 2$;

б) $A$ — матрица $2 \times 5$, $B$ — матрица $5 \times 3$;

в) $A$ — матрица $8 \times 3$, $B$ — матрица $3 \times 8$;

г) $A$ — квадратная матрица $4 \times 4$, $B$ — квадратная матрица $4 \times 4$.
    
**Решение**

Для того, чтобы произведение матриц было определено, необходимо, чтобы число столбцов первой матрицы совпадало с числом строк второй матрицы.
 
а) $A$ — матрица $4 \times 2$, $B$ — матрица $4 \times 2$.

Число столбцов матрицы $A = 2$, число строк в матрице $B = 4$, значит умножение матриц $AB$ *не определено*.
    
Число столбцов матрицы $B = 2$, число строк в матрице $A = 4$, значит умножение матриц $BA$ *не определено*.

б) $A$ — матрица $2 \times 5$, $B$ — матрица $5 \times 3$.

Число столбцов матрицы $A = 5$, число строк в матрице $B = 5$, значит умножение матриц $AB$ *определено*.
    
Результирующая матрица $C = AB$ будет иметь размерность $2 \times 3$.
    
Число столбцов матрицы $B = 3$, число строк в матрице $A = 2$, значит умножение матриц $BA$ *не определено*.
    
в) $A$ — матрица $8 \times 3$, $B$ — матрица $3 \times 8$.

Число столбцов матрицы $A = 3$, число строк в матрице $B = 3$, значит умножение матриц $AB$ *определено*.
    
Результирующая матрица $C = AB$ будет иметь размерность $8 \times 8$.
    
Число столбцов матрицы $B = 8$, число строк в матрице $A = 8$, значит умножение матриц $BA$ *определено*.
    
Результирующая матрица $C = BA$ будет иметь размерность $3 \times 3$.
    
г) $A$ — квадратная матрица $4 \times 4$, $B$ — квадратная матрица $4 \times 4$.

Матрицы $A$ и $B$ являются квадратными размерности $4 \times 4$, значит произведения матриц $AB$ и $BA$ *определены*.
    
Результирующие матрицы $C_1 = AB$ и $C_2 = BA$ будут иметь размерность $4 \times 4$.
 
**Ответ (задание 1):** <br>
а) $AB$ - нет, $BA$ - нет, <br>
б) $AB$ - да $2 \times 3$, $BA$ - нет; <br>
в) $AB$ - да $8 \times 8$, $BA$ - да $3 \times 3$; <br>
г) $AB$ - да $4 \times 4$, $BA$ - да $4 \times 4$.

### Задание 2 <a class='anchor' id='matrix1_2'>
    
Найдите сумму и произведение матриц 
$A = \begin{pmatrix}
1 & -2 \\ 
3 & 0
\end{pmatrix}$ и 
$B = \begin{pmatrix}
4 & -1 \\ 
0 & 5
\end{pmatrix}.$
    
**Решение**
 
Сумма матриц:

$$
A + B = 
\begin{pmatrix}
1 & -2 \\ 
3 & 0
\end{pmatrix} + 
\begin{pmatrix}
4 & -1 \\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1 + 4 & -2 - 1 \\ 
3 + 0 & 0 + 5
\end{pmatrix} =
\begin{pmatrix}
5 & -3 \\ 
3 & 5
\end{pmatrix}.
$$
    
Произведение матриц:
    
$$
A \cdot B = 
\begin{pmatrix}
1 & -2 \\ 
3 & 0
\end{pmatrix} \cdot 
\begin{pmatrix}
4 & -1 \\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1 \cdot 4 + (-2) \cdot 0 & 1 \cdot (-1) + (-2) \cdot 5  \\ 
3 \cdot 4 + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5
\end{pmatrix} =
\begin{pmatrix}
4 & -11 \\ 
12 & -3
\end{pmatrix}.
$$

In [2]:
# Проверка через numpy
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

sum_AB = A + B
dot_AB = np.dot(A, B)

print(f'A + B = \n{sum_AB}')
print(f'A * B = \n{dot_AB}')

A + B = 
[[ 5 -3]
 [ 3  5]]
A * B = 
[[  4 -11]
 [ 12  -3]]


**Ответ (задание 2):** 
$
A + B = 
\begin{pmatrix}
5 & -3 \\ 
3 & 5
\end{pmatrix}$,
$
A \cdot B = 
\begin{pmatrix}
4 & -11 \\ 
12 & -3
\end{pmatrix}
$.

### Задание 3 <a class='anchor' id='matrix1_3'>
    
Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A - 2B + 4C$ для матриц 
$A = \begin{pmatrix}
1 & 7 \\ 
3 & -6
\end{pmatrix}
$, 
$B = \begin{pmatrix}
0 & 5 \\ 
2 & -1
\end{pmatrix}$,
$C = \begin{pmatrix}
2 & -4 \\ 
1 & 1
\end{pmatrix}.$
    
**Решение**

$$
3A - 2B + 4C = 
3 \begin{pmatrix}
1 & 7 \\ 
3 & -6
\end{pmatrix} - 
2 \begin{pmatrix}
0 & 5 \\ 
2 & -1
\end{pmatrix} + 
4 \begin{pmatrix}
2 & -4 \\ 
1 & 1
\end{pmatrix} = 
\begin{pmatrix}
3 & 21 \\ 
9 & -18
\end{pmatrix} - 
\begin{pmatrix}
0 & 10 \\ 
4 & -2
\end{pmatrix} + 
\begin{pmatrix}
8 & -16 \\ 
4 & 4
\end{pmatrix} = 
\begin{pmatrix}
11 & -5 \\ 
9 & -12
\end{pmatrix}.
$$

In [3]:
# Проверка через numpy
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

A_3 = 3 * A
B_2 = 2 * B
C_4 = 4 * C
lin_comb = A_3 - B_2 + C_4

print(f'3A = \n{A_3}\n2B = \n{B_2}\n4C = \n{C_4}')
print(f'3A - 2B + 4C = \n{lin_comb}')

3A = 
[[  3  21]
 [  9 -18]]
2B = 
[[ 0 10]
 [ 4 -2]]
4C = 
[[  8 -16]
 [  4   4]]
3A - 2B + 4C = 
[[ 11  -5]
 [  9 -12]]


**Ответ (задание 3):** 
$
3A - 2B + 4C = 
\begin{pmatrix}
11 & -5 \\ 
9 & -12
\end{pmatrix}
$

### Задание 4 <a class='anchor' id='matrix1_4'>
    
Дана матрица $A = \begin{pmatrix}
4 & 1 \\ 
5 & -2 \\ 
2 & 3
\end{pmatrix}$.

Вычислите $AA^T$ и $A^TA$.
    
**Решение**
    
Транспонированная матрица:
    
$$
A^T = \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3 \\
\end{pmatrix}.
$$
    
Произведение матриц:
    
$$
AA^T = \begin{pmatrix}
4 & 1 \\ 
5 & -2 \\ 
2 & 3
\end{pmatrix} \cdot
\begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3 \\
\end{pmatrix} = 
\begin{pmatrix}
17 & 18 & 11 \\ 
18 & 29 & 4 \\
11 & 4 & 13 \\
\end{pmatrix}.
$$
    
$$
A^TA = \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3 \\
\end{pmatrix} \cdot
\begin{pmatrix}
4 & 1 \\ 
5 & -2 \\ 
2 & 3
\end{pmatrix} = 
\begin{pmatrix}
45 & 0 \\ 
0 & 14 \\
\end{pmatrix}.
$$

In [4]:
# Проверка через numpy
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'A^T = \n{A.T}')
print(f'A * A^T = \n{A.dot(A.T)}')
print(f'A^T * A = \n{A.T.dot(A)}')

A^T = 
[[ 4  5  2]
 [ 1 -2  3]]
A * A^T = 
[[17 18 11]
 [18 29  4]
 [11  4 13]]
A^T * A = 
[[45  0]
 [ 0 14]]


**Ответ (задание 4):** 
$
AA^T = 
\begin{pmatrix}
17 & 18 & 11 \\ 
18 & 29 & 4 \\
11 & 4 & 13 \\
\end{pmatrix},
$
$
A^TA = 
\begin{pmatrix}
45 & 0 \\ 
0 & 14 \\
\end{pmatrix}.
$

### Задание 5 <a class='anchor' id='matrix1_5'>
    
Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
from itertools import chain
from operator import add, sub


class Order:
    """ Тип обхода по матрице: C - row-major, F - column-major """
    C, F = range(2)


class Matrix:
    """ Класс для описания объекта матрицы """
    def __init__(self, list_of_rows):
        """
        Конструктор класса
        :param list_of_rows: данные матрицы
        :type list_of_rows: List[List[float]]
        """
        if not list_of_rows:
            raise ValueError('Пустой список')
        if len(set(map(len, list_of_rows))) != 1:
            raise ValueError('Строки разной размерности')

        self.data = list_of_rows
        self.rows = len(list_of_rows)
        self.cols = len(list_of_rows[0]) if list_of_rows else 0

    def __add__(self, other):
        if not self.same_dims(other):
            raise ValueError('Разные размерности')
        data_sum = [list(map(add, self.data[i], other.data[i])) for i in range(self.rows)]
        return Matrix(data_sum)

    def __sub__(self, other):
        if not self.same_dims(other):
            raise ValueError('Разные размерности')
        data_sum = [list(map(sub, self.data[i], other.data[i])) for i in range(self.rows)]
        return Matrix(data_sum)

    def __mul__(self, other):
        return self.dot(other)

    def __str__(self):
        return '\n'.join(['\t'.join(map(str, row)) for row in self.data])

    def same_dims(self, other):
        """
        Определяет равны или нет размерности матрицы
        :param other: матрица, с которой происходит сравнение
        :type other: Matrix
        :rtype: bool
        """
        return self.rows == other.rows and self.cols == other.cols

    def get_flatten(self, order=Order.C):
        """
        Возвращает список из элементов матрицы в заданном порядке
        Если Order.C - обход по строкам, если Order.F - по столбцам
        :param order: тип порядка обхода по матрице
        :type order: Order
        :rtype: List[float]
        """
        if order == Order.F:
            return list(chain(*self.data))
        return list(chain(*zip(*self.data)))

    def dot(self, other):
        """
        Возвращает произведение матриц
        :param other: матрица, на которую умножается
        :type other: Matrix
        :rtype: Matrix
        """
        if self.cols != other.rows:
            raise ValueError('Количество столбцов первой матрицы не совпадает с количеством строк второй матрицы')
        data_mul = [[None for _ in range(other.cols)] for _ in range(self.rows)]
        for i in range(self.rows):
            for j in range(other.cols):
                data_mul[i][j] = sum(self.data[i][p] * other.data[p][j] for p in range(self.cols))
        return Matrix(data_mul)

    def transpose(self):
        """
        Возвращает транспонированную матрицу
        :rtype: Matrix
        """
        data = list(map(list, zip(*self.data)))
        return Matrix(data)

In [6]:
# Проверка
A = Matrix([[4, 1], [5, -2], [2, 3]])
A_T = A.transpose()
print(f'A =\n{A}\n')
print(f'A^T =\n{A_T}\n')
print(f'A * A^T =\n{A * A.transpose()}\n')
print(f'A * A^T =\n{A.dot(A_T)}')

A =
4	1
5	-2
2	3

A^T =
4	5	2
1	-2	3

A * A^T =
17	18	11
18	29	4
11	4	13

A * A^T =
17	18	11
18	29	4
11	4	13


# Матрицы и матричные операции. Часть 2 <a class='anchor' id='matrix2'>

### Задание 1 <a class='anchor' id='matrix2_1'>
    
Вычислите определитель.

**Решение**
    
а)
$
\begin{vmatrix}
\sin x & -\cos x \\ 
\cos x & \sin x
\end{vmatrix} = \sin^2 x + \cos^2 x = 1.
$

б)
$
\begin{vmatrix}
4 & 2 & 3 \\ 
0 & 5 & 1 \\ 
0 & 0 & 9
\end{vmatrix} =
4 \begin{vmatrix}
5 & 1 \\ 
0 & 9 \\ 
\end{vmatrix} = 4 (5 \cdot 9 - 0 \cdot 1) = 4 \cdot 45 = 180.
$

в) 
$
\begin{vmatrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9
\end{vmatrix} = 
1 \begin{vmatrix}
5 & 6 \\ 
8 & 9 
\end{vmatrix} - 
2 \begin{vmatrix}
4 & 6 \\ 
7 & 9 
\end{vmatrix} +
3 \begin{vmatrix}
4 & 5 \\ 
7 & 8 
\end{vmatrix} = (45 - 48) - 2(36 - 42) + 3(32 - 35) = -3 + 12 - 9 = 0.
$

In [7]:
# Проверка через numpy
A_2 = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
A_3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'|A_б| = {np.linalg.det(A_2)}')
print(f'|A_в| = {np.linalg.det(A_3)}')

|A_б| = 180.0
|A_в| = 0.0


**Ответ (задание 1):** <br>
а) $1$ <br>
б) $180$ <br>
в) $0$

### Задание 2 <a class='anchor' id='matrix2_2'>
    
Определитель матрицы $A$ равен $4$. 
    
Найдите:

а) $\text{det}(A^2)$;

б) $\text{det}(A^T)$;

в) $\text{det}(2A)$.
    
**Решение**
    
а) $\text{det}(A^2) = \text{det}(A \cdot A) = \text{det}A \cdot \text{det}A = 4 \cdot 4 = 16$.
    
б) $\text{det}(A^T) = \text{det}A = 4$.

в) $\text{det}(2A) = 2^n \text{det}A = 2^n \cdot 4 = 2^n \cdot 2^2 = 2^{n + 2}$, где $n$ - размерность матрицы.

**Ответ (задание 2):** <br>
а) $16$ <br>
б) $4$ <br>
в) $2^{n + 2}$, где $n$ - размерность матрицы

### Задание 3 <a class='anchor' id='matrix2_3'>
    
Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3 \\ 
4 & -14 & 6 \\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.
    
**Решение**

Матрица является вырожденной, если её определитель равен $0$.
    
Очевидно, что в этой матрице первая и вторая строка - линейно зависимы, так как вторую строку можно получить из первой, умножив первую на $-2$. 
    
Тогда огласно свойствам определитель этой матрицы равен $0$, значит матрица *является* вырожденной. 

Чтобы проверить, вычислим определитель заданной матрицы:
    
$$
\begin{vmatrix}
-2 & 7 & -3 \\ 
4 & -14 & 6 \\ 
-3 & 7 & 13
\end{vmatrix} = 
-2 \begin{vmatrix}
-14 & 6 \\ 
7 & 13 
\end{vmatrix} - 
7 \begin{vmatrix}
4 & 6 \\ 
-3 & 13 
\end{vmatrix} -
3 \begin{vmatrix}
4 & -14 \\ 
-3 & 7 
\end{vmatrix} = -2(-182 - 42) - 7(52 + 18) - 3(28 - 42) = 
$$
$$ = 2 \cdot 224 - 7 \cdot 70 + 3 \cdot 14 = 448 - 490 + 42 = 0.$$
    


In [8]:
# Проверка через numpy
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'|A| = {np.linalg.det(A)}')

|A| = 0.0


**Ответ (задание 3):** матрица является вырожденной, потому что её определитель равен $0$.

### Задание 4 <a class='anchor' id='matrix2_4'>
    
Найдите ранг матрицы.
    
**Решение**
    
а) Определим ранг матрицы
$$
\begin{pmatrix}
1 & 2 & 3 \\ 
1 & 1 & 1 \\ 
2 & 3 & 4 \\
\end{pmatrix}.
$$

Вычтем из третьей строки первую, умноженную на 2:

$$
\begin{pmatrix}
1 & 2 & 3 \\ 
1 & 1 & 1 \\ 
0 & -1 & -2 \\
\end{pmatrix}.
$$
    
Вычтем из второй строки первую:

$$
\begin{pmatrix}
1 & 2 & 3 \\ 
0 & -1 & -2 \\ 
0 & -1 & -2 \\
\end{pmatrix}.
$$
    
Видно, что третья строка является линейной комбинацией первых двух, значит её можно отбросить:

$$
\begin{pmatrix}
1 & 2 & 3 \\ 
0 & -1 & -2 \\ 
\end{pmatrix}.
$$
    
Таким образом, ранг матрицы равен 2.

б) Определим ранг матрицы  
    
$$
\begin{pmatrix}
0 & 0 & 2 & 1 \\ 
0 & 0 & 2 & 2 \\ 
0 & 0 & 4 & 3 \\ 
2 & 3 & 5 & 6
\end{pmatrix}.
$$
    
Переставим первую и четвертую строку местами:
    
$$
\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 2 \\ 
0 & 0 & 4 & 3 \\ 
0 & 0 & 2 & 1 \\ 
\end{pmatrix}.
$$ 

Вычтем из четвертой строки вторую, а из третьей - вторую, умноженную на 2:
    
$$
\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 2 \\ 
0 & 0 & 0 & -1 \\ 
0 & 0 & 0 & -1 \\ 
\end{pmatrix}.
$$ 
    
Вычтем из четвертой строки третью:
    
$$
\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 2 \\ 
0 & 0 & 0 & -1 \\ 
0 & 0 & 0 & 0 \\ 
\end{pmatrix}.
$$
    
Отбросим полученную строку из нулей:
    
$$
\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 2 \\ 
0 & 0 & 0 & -1 \\ 
\end{pmatrix}.
$$ 
    
Таким образом, ранг матрицы равен 3.

In [9]:
# Проверка через numpy
A_1 = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
A_2 = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

print(f'rank_A_а = {np.linalg.matrix_rank(A_1)}')
print(f'rank_A_б = {np.linalg.matrix_rank(A_2)}')

rank_A_а = 2
rank_A_б = 3


**Ответ (задание 4):** <br>
а) $2$ <br>
б) $3$ <br>