# Оглавление
1. [Системы линейных уравнений. Часть 1](#slau1)
    * [Задание 1](#slau1_1)
    * [Задание 2](#slau1_2)
        * [Задание 2.а](#slau1_2_1)
        * [Задание 2.б](#slau1_2_1)
        * [Задание 2.в](#slau1_2_3)
    * [Задание 3](#slau1_3)
    * [Задание 4](#slau1_4)
2. [Системы линейных уравнений. Часть 2](#slau2)
    * [Задание 1](#slau2_1)
        * [Задание 1.а](#slau2_1_1)
        * [Задание 1.б](#slau2_1_2)
    * [Задание 2](#slau2_2)
    * [Задание 3](#slau2_3)
    * [Задание 4](#slau2_4)
    * [Задание 5](#slau2_5)
        * [Метод Крамера](#slau2_5_1)
        * [LU-разложение](#slau2_5_2)
        * [Метод Холецкого](#slau2_5_3)

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

# Системы линейных уравнений. Часть 1 <a class='anchor' id='slau1'>

### Задание 1 <a class='anchor' id='slau1_1'>
    
Решите систему уравнений методом Гаусса:

$$
\begin{cases}
x_1 + x_2 - x_3 - 2x_4 = 0, \\
2x_1 + x_2 - x_3 + x_4 = -2, \\
x_1 + x_2 - 3x_3 + x_4 = 4.
\end{cases}
$$

**Решение**
    
Расширенная матрица системы:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0 \\ 
-2 \\
4
\end{matrix}
\end{pmatrix}.
$$
    
Приведем матрицу к ступенчатому виду. 
    
Для этого сначала вычтем из второй строки первую, умноженную на 2:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0 \\ 
-2 \\
4
\end{matrix}
\end{pmatrix}.
$$
    
Далее прибавим первую строку к третьей:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0 \\ 
-2 \\
4
\end{matrix}
\end{pmatrix}.
$$
    
Из полученной матрицы видно, что система имеет бесконечное число решений. 
    
В качестве свободного параметра возьмем $x_4$, обозначим его через произвольную константу $C$:
    
$$x_4 = C.$$
    
Получим выражения для остальных неизвестных:
    
$$x_3 = -\frac{4 - 3x_4}{2} = \frac{3}{2}C - 2,$$
    
$$x_2 = 2 + 5x_4 + x_3 = 2 + 5c + \frac{3}{2}C - 2 = \frac{13}{2}C,$$
    
$$x_1 = 2x_4 + x_3 - x_2 = 2C + \frac{3}{2}C - 2 - \frac{13}{2}C = -3C - 2.$$
    
**Ответ (задание 1):** общее решение
$\begin{cases}
x_1 = -3C - 2 \\
x_2 = \frac{13}{2}C \\
x_3 = \frac{3}{2}C - 2 \\
x_4 = C
\end{cases}$, где $C$ - произвольная констната

### Задание 2 <a class='anchor' id='slau1_2'>
    
Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:

**Задание 2.а** <a class='anchor' id='slau1_2_1'>
    
$$
\begin{cases}
3x_1 - x_2 + x_3 = 4, \\
2x_1 - 5x_2 - 3x_3 = -17, \\
x_1 + x_2 - x_3 = 0;
\end{cases}
$$

**Решение**
    
Расширенная матрица системы:
        
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\
2 & -5 & -3 \\
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4 \\ 
-17 \\
0
\end{matrix}
\end{pmatrix}.
$$
    
Очевидно, что столбцы исходной матрицы $A$ линейно независимы, а три линейно независимых вектора в трехмерном пространстве образуют базис, и любой другой вектор может быть представлен в виде линейной комбинации этих базисных векторов единственным образом. Поэтому эта система уравнений *совместна* и имеет *единственное решение*.
    
Докажем это утверждение с помощью теоремы Кронекера-Капелли, для этого определим ранги матриц.
    
Переставим строки матрицы:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
2 & -5 & -3 \\
3 & -1 & 1
\end{matrix}\right|
\begin{matrix}
0 \\ 
-17 \\
4
\end{matrix}
\end{pmatrix}.
$$
    
Вычтем из второй строки первую, умноженную на 2:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
0 & -7 & -1 \\
3 & -1 & 1
\end{matrix}\right|
\begin{matrix}
0 \\ 
-17 \\
4
\end{matrix}
\end{pmatrix}.
$$
    
Вычтем из третьей строки первую, умноженную на 3:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
0 & -7 & -1 \\
0 & -4 & 4
\end{matrix}\right|
\begin{matrix}
0 \\ 
-17 \\
4
\end{matrix}
\end{pmatrix}.
$$
    
Разделим третью строку на 4 и поменяем местами со второй строокой:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
0 & -1 & 1 \\
0 & -7 & -1
\end{matrix}\right|
\begin{matrix}
0 \\ 
1 \\
-17
\end{matrix}
\end{pmatrix}.
$$
    
Вычтем из третьей строки вторую, умноженную на -7:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
0 & -1 & 1 \\
0 & 0 & -8
\end{matrix}\right|
\begin{matrix}
0 \\ 
1 \\
-24
\end{matrix}
\end{pmatrix}.
$$
    
Видно, что ранг исходной матрицы совпадает с рангом расширенной, причем ранг равен числу неизвестных:

$$\text{rank} A = \text{rank} \tilde A = 3,$$
    
значит по теореме Кронекера-Капелли система *совместна* и имеет *единственное решение*.
    
**Ответ (задание 2.а):** система совместна и имеет единственное решение

**Задание 2.б** <a class='anchor' id='slau1_2_2'>
    
$$
\begin{cases}
2x_1 - 4x_2 + 6x_3 = 1, \\
x_1 - 2x_2 + 3x_3 = -2, \\
3x_1 - 6x_2 + 9x_3 = 5;
\end{cases}
$$

**Решение**
    
Расширенная матрица системы:
        
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\
1 & -2 & 3 \\
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1 \\ 
-2 \\
5
\end{matrix}
\end{pmatrix}.
$$
    
Очевидно, что столбцы исходной матрицы $A$ линейно зависимы. Это значит, что все они лежат на одной прямой, то есть принадлежат некоторому одномерному подпространству исходного трехмерного.
 
При этом видно, что вектор правой части и столбцы исходной матрицы линейно независимы. Значит, что этот вектор не лежит на той прямой и не принадлежит одномерному линейному подпространству. 
    
Значит вектор правой части не может быть представлен в виде линейной комбинации векторов исходной матрицы, то есть система *несовместна*.
    
Докажем это утверждение с помощью теоремы Кронекера-Капелли, для этого определим ранги матриц.
    
Переставим строки матрицы:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\
2 & -4 & 6 \\
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
-2 \\ 
1 \\
5
\end{matrix}
\end{pmatrix}.
$$
    
Вычтем из второй строки первую, умноженную на 2:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\
0 & 0 & 0 \\
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
-2 \\ 
5 \\
5
\end{matrix}
\end{pmatrix}.
$$

Вычтем из третьей строки первую, умноженную на 3:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
-2 \\ 
5 \\
11
\end{matrix}
\end{pmatrix}.
$$
    
Вычитая из третьей строки вторую, умноженную на $\frac{11}{5}$, получаем нулевую строку, которую можно отбросить:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
-2 \\ 
5
\end{matrix}
\end{pmatrix}.
$$
 
Видно, что ранг исходной матрицы меньше ранга расширенной:

$$\text{rank} A = 1 < \text{rank} \tilde A = 2,$$
    
значит по теореме Кронекера-Капелли система *несовместна*.
    
**Ответ (задание 2.б):** система несовместна

**Задание 2.в** <a class='anchor' id='slau1_2_3'>
    
$$
\begin{cases}
x_1 + 2x_2 + 5x_3 = 4, \\
3x_1 + x_2 - 8x_3 = -2. 
\end{cases}
$$

**Решение**
    
Расширенная матрица системы:
        
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\
3 & 1 & -8
\end{matrix}\right|
\begin{matrix}
4 \\ 
-2
\end{matrix}
\end{pmatrix}.
$$
    
Очевидно, что столбцы исходной матрицы $A$ линейно независимы. Значит в двумерном пространстве любая пара столбцов исходной матрицы образует базис, и любой другой вектор можно единственным образом представить в виде линейной комбинации этих базисных векторов. Из системы видно, что коэффициент при третьем векторе может быть произвольным, значит система имеет *бесконечное количество решений*.
    
Докажем это утверждение с помощью теоремы Кронекера-Капелли, для этого определим ранги матриц.
    
Вычитем из второй строки первую, умноженную на 3:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\
0 & -5 & -23
\end{matrix}\right|
\begin{matrix}
4 \\ 
-14
\end{matrix}
\end{pmatrix}.
$$
    
Видно, что ранг исходной матрицы совпадает с рангом расширенной, причем значение ранга меньше числа неизвестных:
    
$$\text{rank} A = \text{rank} \tilde A = 2 < 3,$$
    
значит по теореме Кронекера-Капелли система *совместна* и имеет *бесконечное количество решений*.
    
**Ответ (задание 2.в):** система совместна и имеет бесконечное количество решений

### Задание 3 <a class='anchor' id='slau1_3'>
    
Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4 \\ 
0 & 5 & 0 & 1 \\ 
0 & 0 & 3 & 0 \\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3 \\ 
2 \\
4 \\
1
\end{matrix}
\end{pmatrix}.$$

**Решение**
    
Очевидно, что ранг исходной матрицы совпадает с рангом расширенной, 

$$\text{rank} A = \text{rank} \tilde A = 3,$$
    
значит согласно теореме Кронекера-Капелли система *совместна* и имеет *единственное решение*.
    
**Ответ (задание 3):** согласно теореме Кронекера-Капелли система совместна и имеет единственное решение

### Задание 4 <a class='anchor' id='slau1_4'>
    
Дана система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a \\ 
b \\
c
\end{matrix}
\end{pmatrix}.$$

Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.

**Решение**
    
Вычтем из второй строки первую, умноженную на 4:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
0 & -3 & -6 \\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a \\ 
b - 4a \\
c
\end{matrix}
\end{pmatrix}.
$$
    
Вычтем из третьей строки первую, умноженную на 7:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
0 & -3 & -6 \\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a \\ 
b - 4a \\
c - 7a
\end{matrix}
\end{pmatrix}.
$$
    
Вычтем из третьей строки вторую, умноженную на 2:
    
$$
\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
0 & -3 & -6 \\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a \\ 
b - 4a \\
c - 7a - 2b + 8a
\end{matrix}
\end{pmatrix}.
$$
    
Таким образом, получили следующее неравенство для того, чтобы система считалась несовместной:
    
$$c - 7a - 2b + 8a \neq 0 \; \Rightarrow \; c + a - 2b \neq 0.$$
    
**Ответ (задание 4):** $c + a - 2b \neq 0$

# Системы линейных уравнений. Часть 2 <a class='anchor' id='slau2'>

In [2]:
def is_correct_LU(A, L, U):
    """ 
    Проверяет правильность LU-разложения и выводит результат в консоль
    :param A: исходная матрица
    :param L: матрица L, полученная в ходе разложения
    :param U: матрица U, полученная в ходе разложения
    """
    is_correct = np.isclose(A, L @ U).all()
    print(f'A == L @ U: {is_correct}')

In [3]:
def show_solve_result(A, b):
    """ 
    Решает систему линейных уравнений и выводит результат в консоль
    :param A: матрица коэффициентов системы
    :param b: вектор правой части
    """
    print(f'Решение x = {np.linalg.solve(A, b)}')

### Задание 1 <a class='anchor' id='slau2_1'>
    
Решите систему уравнений методом Крамера:

**Задание 1.а** <a class='anchor' id='slau2_1_1'>
    
$$\begin{cases}
x_1 - 2x_2 = 1 \\
3x_1 - 4x_2 = 7
\end{cases}$$
    
**Решение**
    
Матрица коэффициентов:
    
$$A = \begin{pmatrix}
1 & -2 \\ 
3 & -4
\end{pmatrix}.$$
    
Вычислим определитель матрицы коэффициентов
    
$$
\text{det}A = \begin{vmatrix}
1 & -2 \\ 
3 & -4
\end{vmatrix} = -4 + 6 = 2.
$$
    
Определитель матрицы $\text{det}A = 2 \neq 0$ значит система совестна.
    
Вычислим определитель матрицы, у которой первый столбец заменен правой частью:
    
$$
\text{det}A_1 = \begin{vmatrix}
1 & -2 \\ 
7 & -4
\end{vmatrix} = -4 + 14 = 10.
$$
    
Вычислим определитель матрицы, у которой второй столбец заменен правой частью:
    
$$
\text{det}A_2 = \begin{vmatrix}
1 & 1 \\ 
3 & 7
\end{vmatrix} = 7 - 3 = 4.
$$
    
Найдем решение системы по формулам Крамера:
    
$$x_1 = \frac{\text{det}A_1}{\text{det}A} = \frac{10}{2} = 5,$$
    
$$x_2 = \frac{\text{det}A_2}{\text{det}A} = \frac{4}{2} = 2.$$

In [4]:
# Проверка правильности решения
A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])
show_solve_result(A, b)

Решение x = [5. 2.]


**Ответ (задание 1.а):** $(5, 2)$

**Задание 1.б** <a class='anchor' id='slau2_1_2'>
    
$$\begin{cases}
2x_1 - x_2 + 5x_3 = 10 \\
x_1 + x_2 - 3x_3 = -2 \\
2x_1 + 4x_2 + x_3 = 1
\end{cases}$$
    
**Решение**
    
Матрица коэффициентов:
    
$$A = \begin{pmatrix}
2 & -1 & 5 \\
1 & 1 & -3 \\
2 & 4 & 1
\end{pmatrix}.$$
    
Вычислим определитель матрицы коэффициентов, разложив по второй строке:
    
$$
\text{det}A = \begin{vmatrix}
2 & -1 & 5 \\
1 & 1 & -3 \\
2 & 4 & 1
\end{vmatrix} =
-\begin{vmatrix}
-1 & 5 \\
4 & 1
\end{vmatrix} + 
\begin{vmatrix}
2 & 5 \\
2 & 1
\end{vmatrix} + 
3 \begin{vmatrix}
2 & -1 \\
2 & 4
\end{vmatrix} = 21 -8 + 30 = 43.
$$
    
Определитель матрицы $\text{det}A = 43 \neq 0$ значит система совестна.
    
Вычислим определитель матрицы, у которой первый столбец заменен правой частью (разложение по 3 строке):
    
$$
\text{det}A_1 = \begin{vmatrix}
10 & -1 & 5 \\
-2 & 1 & -3 \\
1 & 4 & 1
\end{vmatrix} = 
\begin{vmatrix}
-1 & 5 \\
1 & -3
\end{vmatrix} -
4 \begin{vmatrix}
10 & 5 \\
-2 & -3
\end{vmatrix} + 
\begin{vmatrix}
10 & -1 \\
-2 & 1
\end{vmatrix} = -2 + 80 + 8 = 86.
$$
    
Вычислим определитель матрицы, у которой второй столбец заменен правой частью (разложение по 3 строке):
    
$$
\text{det}A_2 = \begin{vmatrix}
2 & 10 & 5 \\
1 & -2 & -3 \\
2 & 1 & 1
\end{vmatrix} =
2\begin{vmatrix}
10 & 5 \\
-2 & -3
\end{vmatrix} -
\begin{vmatrix}
2 & 5 \\
1 & -3
\end{vmatrix} + 
\begin{vmatrix}
2 & 10 \\
1 & -2
\end{vmatrix} = -40 + 11 - 14 = -43.
$$
    
Вычислим определитель матрицы, у которой третий столбец заменен правой частью (разложение по 2 строке):
    
$$
\text{det}A_3 = \begin{vmatrix}
2 & -1 & 10 \\
1 & 1 & -2 \\
2 & 4 & 1
\end{vmatrix} =
-\begin{vmatrix}
-1 & 10 \\
4 & 1
\end{vmatrix} +
\begin{vmatrix}
2 & 10 \\
2 & 1
\end{vmatrix} + 
2 \begin{vmatrix}
2 & -1 \\
2 & 4
\end{vmatrix} = 41 - 18 + 20 = 43.
$$
    
Найдем решение системы по формулам Крамера:
    
$$x_1 = \frac{\text{det}A_1}{\text{det}A} = \frac{86}{43} = 2,$$
    
$$x_2 = \frac{\text{det}A_2}{\text{det}A} = -\frac{43}{43} = -1.$$
    
$$x_3 = \frac{\text{det}A_3}{\text{det}A} = \frac{43}{43} = 1.$$

In [5]:
# Проверка правильности решения
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])
show_solve_result(A, b)

Решение x = [ 2. -1.  1.]


**Ответ (задание 1.б):** $(2, -1, 1)$

### Задание 2 <a class='anchor' id='slau2_2'>
    
Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

**Задание 2.а** <a class='anchor' id='slau2_2_1'>
    
$$
A = \begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}
$$
    
**Решение**
   
Домножим первую строку на 2 и вычтем её из второй строки:
    
$$
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix},
$$
    
значит в матрице $L$ элемент $l_{21} = 2$.
    
Далее вычтем из третьей строки первую, умноженную на 3:
    
$$
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix},
$$
    
значит в матрице $L$ элемент $l_{31} = 3$.
    
Вычтем из третьей строки вторую, умноженную на 4:

$$
U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix},
$$
    
значит в матрице $L$ элемент $l_{32} = 4$.
    
Таким образом, получаем матрицу $L$ следующего вида:
    
$$
L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}.
$$

In [6]:
# Проверка правильности разложения
L = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])
U = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
is_correct_LU(A, L, U)

A == L @ U: True


**Ответ (задание 2.а):** 
$
L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}
$

**Задание 2.б** <a class='anchor' id='slau2_2_2'>
    
$$
A = \begin{pmatrix}
1 & 1 & 2 & 4 \\ 
2 & 5 & 8 & 9 \\ 
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{pmatrix}
$$
    
**Решение**
    
Вычтем из второй строки первую, умноженную на 2:
    
$$
\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{pmatrix}
$$
 
значит в матрице $L$ элемент $l_{21} = 2$.
    
Вычтем из третьей строки первую, умноженную на 3:
    
$$
\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
4 & 22 & 53 & 33
\end{pmatrix}
$$
 
значит в матрице $L$ элемент $l_{31} = 3$.
    
Вычтем из четвертой строки первую, умноженную на 4:
    
$$
\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
0 & 18 & 45 & 17
\end{pmatrix}
$$
 
значит в матрице $L$ элемент $l_{41} = 4$.
    
Вычтем из третьей строки вторую, умноженную на 5:
    
$$
\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 18 & 45 & 17
\end{pmatrix}
$$
 
значит в матрице $L$ элемент $l_{32} = 5$.
    
Вычтем из четвертой строки вторую, умноженную на 6:
    
$$
\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 21 & 11
\end{pmatrix}
$$
 
значит в матрице $L$ элемент $l_{42} = 6$.
    
Вычтем из четвертой строки третью, умноженную на 7:
    
$$
U = \begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 0 & 4
\end{pmatrix}
$$
 
значит в матрице $L$ элемент $l_{43} = 7$.
    
Таким образом, получаем матрицу $L$ следующего вида:
    
$$
L = \begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}.
$$
    
**Ответ (задание 2.б):** 
$
L = \begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}
$

In [7]:
# Проверка правильности разложения
L = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])
U = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
is_correct_LU(A, L, U)

A == L @ U: True


### Задание 3 <a class='anchor' id='slau2_3'>
    
Решите систему линейных уравнений методом $LU$-разложения:

$$
\begin{cases}
2x_1 + x_2 + 3x_3 = 1 \\
11x_1 + 7x_2 + 5x_3 = -6 \\
9x_1 + 8x_2 + 4x_3 = -5
\end{cases}
$$

**Решение**
    
Матрица коэффициентов:
    
$$
A = \begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}.
$$
    
Правая часть:
    
$$
b = \begin{pmatrix}
1 \\ 
-6 \\ 
-5
\end{pmatrix}.
$$
    
Определим матрицы $L$, $U$.
    
Вычтем из второй строки первую, умноженную на $\frac{11}{2}$:
    
$$
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
9 & 8 & 4
\end{pmatrix}.
$$
    
значит в матрице $L$ элемент $l_{21} = \frac{11}{2}$.
    
Вычтем из третьей строки первую, умноженную на $\frac{9}{2}$:
    
$$
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & \frac{7}{2} & -\frac{19}{2}
\end{pmatrix}.
$$
    
значит в матрице $L$ элемент $l_{31} = \frac{9}{2}$.
    
Вычтем из третьей строки вторую, умноженную на $\frac{7}{3}$:
    
$$
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}.
$$
    
значит в матрице $L$ элемент $l_{32} = \frac{7}{3}$.
    
Таким образом, получили матрицы следующего вида:
    
$$
U = \begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}.
$$
    
$$
L = \begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}.
$$
    
Решим систему:
    
$$Ly = b,$$

или

$$
\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}
\begin{pmatrix}
y_1 \\ 
y_2 \\ 
y_3
\end{pmatrix} = 
\begin{pmatrix}
1 \\ 
-6 \\ 
-5
\end{pmatrix}.
$$
    
Распишем уравнения:

$$
\begin{cases}
y_1 = 1 \\
\frac{11}{2}y_1 + y_2 = -6 \\
\frac{9}{2}y_1 - \frac{7}{3}y_2 + y_3 = -5
\end{cases}.
$$
    
Решение этой системы:
    
$$
\begin{cases}
y_1 = 1 \\
y_2 = -6 - \frac{11}{2}y_1 = -6 - \frac{11}{2} = -\frac{23}{2} \\
y_3 = -5 - \frac{9}{2}y_1 + \frac{7}{3}y_2 = -5 - \frac{9}{2} - \frac{7}{3} \cdot \frac{23}{2} = \frac{104}{6}
\end{cases}.
$$
    
Решим систему 
    
$$Ux = y$$
    
или

$$
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & \frac{3}{2} & -\frac{23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix}
\begin{pmatrix}
x_1 \\ 
x_2 \\ 
x_3
\end{pmatrix} = 
\begin{pmatrix}
1 \\ 
-\frac{23}{2} \\ 
\frac{104}{6}
\end{pmatrix}.
$$
    
Распишем уравнения:

$$
\begin{cases}
2x_1 + x_2 + 3x_3 = 1 \\
\frac{3}{2}x_2 - \frac{23}{2}x_3 = -\frac{23}{2} \\
\frac{52}{3}x_3 = \frac{104}{6}
\end{cases}.
$$
    
Распишем для каждой переменной:
    
$$x_3 = \frac{104}{6} \cdot \frac{3}{52} = 1,$$
    
$$\frac{3}{2}x_2 = -\frac{23}{2} + \frac{23}{2}x_3 = 0 \; \Rightarrow \; x_2 = 0,$$
    
$$2x_1 = 1 - x_2 - 3x_3 = 1 -3 = -2 \; \Rightarrow \; x_1 = -1.$$
    
Таким образом, получили решение системы:
    
$$
\begin{cases}
x_1 = -1 \\
x_2 = 0 \\
x_3 = 1
\end{cases}.
$$

In [8]:
# Проверка правильности разложения
L = np.array([[1, 0, 0], [11/2, 1, 0], [9/2, 7/3, 1]])
U = np.array([[2, 1, 3], [0, 3/2, -23/2], [0, 0, 52/3]])
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
is_correct_LU(A, L, U)

# Проверка правильности решения
b = np.array([1, -6, -5])
show_solve_result(A, b)

A == L @ U: True
Решение x = [-1.  0.  1.]


**Ответ (задание 3):** $(-1, 0, 1)$

### Задание 4 <a class='anchor' id='slau2_4'>
    
Решите систему линейных уравнений методом Холецкого:

$$\begin{cases}
81x_1 - 45x_2 + 45x_3 = 531 \\
-45x_1 + 50x_2 - 15x_3 = -460 \\
45x_1 - 15x_2 + 38x_3 = 193
\end{cases}$$

**Решение**
    
Матрица коэффициентов:
    
$$
A = \begin{pmatrix}
81 & -45 & 45 \\ 
-45 & 50 & -15 \\ 
45 & -15 & 38
\end{pmatrix}.
$$
    
Правая часть:
    
$$
b = \begin{pmatrix}
531 \\ 
-460 \\ 
193
\end{pmatrix}.
$$
    
Вычислим элементы матрицы $L$:
    
$$l_{11} = \sqrt{a_{11}} = \sqrt{81} = 9,$$
    
$$l_{21} = \frac{a_{21}}{l_{11}} = -\frac{45}{9} = -5,$$
    
$$l_{31} = \frac{a_{31}}{l_{11}} = \frac{45}{9} = 5,$$

$$l_{22} = \sqrt{a_{22} - l_{21}^{2}}=\sqrt{50 - 25} = \sqrt{25} = 5,$$
    
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right) = \frac{1}{5}(-15 + 25) = 2,$$

$$l_{33} = \sqrt{a_{33} - l_{31}^{2} - l_{32}^{2}} = \sqrt{38 - 25 - 4} = \sqrt{9} = 3.$$

Таким образом, получили матрицы:
    
$$
L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix},
$$
    
$$
L^T = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.
$$
    
Решим систему:
    
$$Ly = b,$$

или

$$
\begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}
\begin{pmatrix}
y_1 \\ 
y_2 \\ 
y_3
\end{pmatrix} = 
\begin{pmatrix}
531 \\ 
-460 \\ 
193
\end{pmatrix}.
$$
    
Распишем уравнения:

$$
\begin{cases}
9y_1 = 531 \\
-5y_1 + 5y_2 = -460 \\
5y_1 + 2y_2 + 3y_3 = 193
\end{cases}.
$$
    
Распишем решение для каждой переменной:
    
$$y_1 = \frac{531}{9} = 59,$$
    
$$-5y_1 + 5y_2 = -460 \; \Rightarrow \; -y_1 + y_2 = -92 \; \Rightarrow \; y_2 = -92 + y_1 = -92 + 59 = -33,$$
    
$$5y_1 + 2y_2 + 3y_3 = 193 \; \Rightarrow \; 3y_3 = 193 - 5y_1 - 2y_2 - 193 - 295 + 66 = -36 \; \Rightarrow \; y_3 = -12.$$
    
Решение этой системы:
    
$$
\begin{cases}
y_1 = 59 \\
y_2 = -33 \\
y_3 = -12
\end{cases}.
$$
    
Теперь решим систему:
    
$$L^T x = y,$$

или

$$
\begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
x_1 \\ 
x_2 \\ 
x_3
\end{pmatrix} = 
\begin{pmatrix}
59 \\ 
-33 \\ 
-12
\end{pmatrix}.
$$
    
Распишем уравнения:

$$
\begin{cases}
9x_1 - 5x_2 + 5x_3 = 59 \\
5x_2 + 22x_3 = -33 \\
3x_3 = -12
\end{cases}.
$$
    
Распишем решение для каждой переменной:
    
$$x_3 = -\frac{12}{3} = -4,$$
    
$$5x_2 = -33 - 2x_3 = -33 + 8 = -25 \; \Rightarrow \; x_2 = -5,$$
    
$$9x_1 = 59 + 5x_2 - 5x_3 = 59 - 25 + 20 = 54 \; \Rightarrow \; x_1 = 6.$$
    
Таким образом, получаем решение исходной системы:
    
$$
\begin{cases}
x_1 = 6 \\
x_2 = -5 \\
x_3 = -4
\end{cases}.
$$

In [9]:
# Проверка правильности решения
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])
show_solve_result(A, b)

Решение x = [ 6. -5. -4.]


In [10]:
# Матрица L разложения Холецкого
L = np.linalg.cholesky(A)
print(f'Матрица L =\n{L}')

Матрица L =
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]


**Ответ (задание 4):** $(6, -5, -4)$

### Задание 5 <a class='anchor' id='slau2_5'>
    
Напишите на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

Заведем матрицы из заданий части 2 для проверки реализованных алгоритмов.

[Задание 1.а (Метод Крамера)](#slau2_1_1)

In [11]:
A_cr1 = np.array([[1, -2], [3, -4]])
b_cr1 = np.array([1, 7])

[Задание 1.б (Метод Крамера)](#slau2_1_2)

In [12]:
A_cr2 = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b_cr2 = np.array([10, -2, 1])

[Задание 3 (LU-разложение)](#slau2_3)

In [13]:
A_lu = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b_lu = np.array([1, -6, -5])

[Задание 4 (Метод Холецкого)](#slau2_4)

In [14]:
A_ch = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b_ch = np.array([531, -460, 193])

Определим общую функцию для решения системы с треугольной матрицей

In [15]:
def solve_triangle(A, b, reverse=False):
    """
    Решает систему уравнений для треугольной матрицы
    :param A: матрица коэффициентов
    :param b: правая часть
    :param reverse: решение для нижнетреугольной или верхнетреугольной матрицы
    :rtype: np.array
    """
    n_rows, n_cols = A.shape
    
    # Вектор решения     
    x = np.zeros(n_rows)
    indexes = range(n_rows) if not reverse else reversed(range(n_rows))
    for i in indexes:
        I = np.r_[0:i, i:n_cols]
        x[i] = (b[i] - x[I] @ A[i, I]) / A[i, i]
    return x

**Правило Крамера** <a class='anchor' id='slau2_5_1'>

In [16]:
def cramer(A, b):
    """ 
    Решает систему равнений с помощью правила Крамера
    :param A: матрица коэффициентов системы
    :param b: вектор правой части
    :rtype: np.array
    """
    if A.shape[0] != A.shape[1]:
        raise Exception('Матрица не квадратная')
        
    # Определитель матрицы     
    det_A = np.linalg.det(A)
    if np.isclose(det_A, 0.0):
        raise Exception('Матрица вырождена')
    
    # Вектор решения     
    x = np.zeros(b.size)
    for col in range(A.shape[1]):
        A_i = np.copy(A)
        # Заменяем столбец матрицы A правой частью
        A_i[:, col] = b
        # Вычисляем значение неизвестной
        x[col] = np.linalg.det(A_i) / det_A
    return x

In [17]:
# Правильный ответ (5, 2)
cramer(A_cr1, b_cr1)

array([5., 2.])

In [18]:
# Правильный ответ (2, -1, 1)
cramer(A_cr2, b_cr2)

array([ 2., -1.,  1.])

In [19]:
# Правильный ответ (-1, 0, 1)
cramer(A_lu, b_lu)

array([-1.,  0.,  1.])

In [20]:
# Правильный ответ (6, -5, -4)
cramer(A_ch, b_ch)

array([ 6., -5., -4.])

**LU-разложение** <a class='anchor' id='slau2_5_2'>

In [21]:
def lu(A, b):
    """
    Решает систему уравнений с помощью LU-разложения
    :param A: матрица коэффициентов системы
    :param b: вектор правой части
    :rtype: np.array
    """
    n_rows, n_cols = A.shape
    
    if n_rows != n_cols:
        raise Exception('Матрица не квадратная')
        
    if np.isclose(np.linalg.det(A), 0.0):
        raise Exception('Матрица вырождена')
    
    # Матрицы LU-разложения     
    U = np.zeros(A.shape)
    L = np.eye(n_rows)
    
    # Вычислим матрицы LU-разложения     
    for i in range(n_rows):
        for j in range(n_cols):
            if i <= j:
                U[i, j] = A[i, j] - L[i, :i] @ U[:i, j]
            if i > j:
                L[i, j] = (A[i, j] - L[i, :j] @ U[:j, j]) / U[j, j]
    
    # Решаем систему Ly = b
    y = solve_triangle(L, b)
    # Решаем систему Ux = y
    x = solve_triangle(U, y, reverse=True)
    
    return x

In [22]:
# Правильный ответ (5, 2)
lu(A_cr1, b_cr1)

array([5., 2.])

In [23]:
# Правильный ответ (2, -1, 1)
lu(A_cr2, b_cr2)

array([ 2., -1.,  1.])

In [24]:
# Правильный ответ (-1, 0, 1)
lu(A_lu, b_lu)

array([-1.,  0.,  1.])

In [25]:
# Правильный ответ (6, -5, -4)
lu(A_ch, b_ch)

array([ 6., -5., -4.])

**Метод Холецкого** <a class='anchor' id='slau2_5_3'>

In [26]:
def is_symmetric(A):
    """
    Определяет, является ли матрица симметричной
    :param A: иссследуемая матрица
    :rtype: bool
    """
    return np.allclose(A, A.T)

def is_positive_defined(A):
    """
    Определяет, является ли матрица положительно определенной
    :param A: иссследуемая матрица
    :rtype: bool
    """
    return np.all(np.linalg.eigvals(A) > 0)


def cholesky(A, b):
    """
    Решает систему уравнений с помощью метода Холецкого
    :param A: матрица коэффициентов системы, невырожденная, симметричная и положительно определенная
    :param b: вектор правой части
    :rtype: np.array
    """
    if np.isclose(np.linalg.det(A), 0.0):
        raise Exception('Матрица вырождена')
        
    if not is_symmetric(A):
        raise Exception('Матрица не симметричная')
        
    if not is_positive_defined(A):
        raise Exception('Матрица не является положительно определенной')
    
    L = np.zeros(A.shape)
    # Алгоритм расчета матрицы L методом Холецкого     
    for i in range(A.shape[0]):
        for j in range(i + 1):
            L[i, j] = np.sqrt(A[i, j] - L[i, :i] @ L[i, :i]) if i == j else (A[i, j] - L[i, :j] @ L[j, :j]) / L[j, j]
    
    # Решаем систему Ly = b
    y = solve_triangle(L, b)
    # Решаем систему L^Tx = y
    x = solve_triangle(L.T, y, reverse=True)
    
    return x

In [27]:
# Правильный ответ (6, -5, -4)
cholesky(A_ch, b_ch)

array([ 6., -5., -4.])